### ISSUE TITLE
One ordre renewal, two payment processed on stripe

### ISSUE THREAD

**Issue by heavestudio** [Automattic/woocommerce-subscriptions-core#636] opened 2024-06-24 19:09 UTC
Using both woocommerce subscription and woocommerce stripe payment gateway.

everything was working fine, but for more than a week i can see that every order on the website create two payment request on stripe.

Only one api webhook active.

Tried to remove totaly the connection between the site and stripe and reset.

Change the way cron are triggered.

Nothing changes, still have a duplicate payement for every order

**Comment by csmcneill** [comment] 2024-06-25 21:33
Howdy @heavestudio! This isn't an issue that we've had similar reports on. It may also be an issue with the Stripe integration on the site — I also see that you opened up https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3220 — but we will need to investigate a bit further to better determine the cause of the issue.

GitHub is not a dedicated support channel, so I recommend connecting with our dedicated support team to look into this further.

Please contact us at <a href="https://woocommerce.com/my-account/contact-support/">WooCommerce.com > My Account > Support</a>. You may need to create an account before you can access that page. We will be able to help you further there.

I will close this issue for now, but we can reopen it if it is an issue that we can duplicate and can confirm is related to the Subscriptions core package for WooCommerce and not [Woo Subscriptions](https://woocommerce.com/products/woocommerce-subscriptions/).

**Closed as not planned by csmcneill** 2024-06-25 21:33 UTC
Labels: category: won't fix
