### ISSUE TITLE
Charges in value for cost on Manually Added Subscriptions 

### ISSUE THREAD

**Issue by jarredAwesome** [Automattic/woocommerce-subscriptions-core#601] opened 2024-04-09 13:52 UTC
The Value of things like tax and shipping on a manually added subscription change when it's time to pay.

To Reproduce:
Admin Side:
Step 1. goto Woo Commerce -> Subscriptions -> Add New Subscriptions
Step 2. Create a new subscription add a product, a shipping charge that isn't your standard shipping rate, and leave tax blank. (for demo purposes, bill it to a demo account you have access to). Click Recalculate/
Step 3. Set Subscriptions Status to Active and update order
Step 4. click "Process Renewal" from the "choose action" dropdown, and submit it

Client Side:
Step 1. log into the client account associated with the subscription you just made
step 2. goto Your Account - > Subscriptions -> the order you just made. Note that everything looks exactly as you typed it in
Step 3. Goto Orders -> Pay (Associated with the Renewal that you just made) you will see it brings you to your normal checkout. This is where the problem is, all the manually added shipping information and tax information gets overwritten. This is a problem because it prevents people from making custom subscriptions.

### Expected behavior
The totals being collected should match what was manually entered in the order.

### Actual behavior
Woo commerce directs you to the checkout page instead of the "play for order" page. This causes the system to automatically recalculate the shipping and tax on the items in the order. Even if you had added already in the creation of the order.

Note:
    I accept the fact this might be a UTS error on my own part. I create subscriptions this way because I sometimes have to create a custom product. Doing it this way means I can charge the unique pricing and have the client pay by loging into their account. If this is a case of me using the plugin incorrectly I appologize. However, it seems counter intuitive to have me enter in information that is going to be disregarded at checkout

**Comment by james-allan** [comment] 2024-04-11 00:04
Hey @jarredAwesome 👋 

Thanks for filing this issue. This is a duplicate of an existing issue https://github.com/Automattic/woocommerce-subscriptions-core/issues/513.

I'm going to close this in favour of keeping discussions about a fix in 1 place. I've made a note on that issue pointing to this report. 🙂

**Closed as completed by james-allan** 2024-04-11 00:04 UTC
Labels: type: bug
