### ISSUE TITLE
Prevent noisy false positive errors when subscription trial period ends (due to recent change in Action Scheduler)

### ISSUE THREAD

**Issue by darcie** [Automattic/woocommerce-subscriptions-core#255] opened 2022-11-08 01:40 UTC
## Describe the bug
When a trial ends, WCS triggers action `woocommerce_scheduled_subscription_trial_end` which is empty by default. WCS doesn't need to do any processing, the action is there for extensibility.

In recent Action Scheduler, empty callbacks trigger an error. 

Our error handling code is showing this error to merchants in the dashboard, which is not necessary (as it's not causing any problems). See [WCS_Failed_Scheduled_Action_Manager::log_action_scheduler_failure()](https://github.com/Automattic/woocommerce-subscriptions-core/blob/trunk/includes/class-wcs-failed-scheduled-action-manager.php#L77).

#### Proposed fix
[WCS_Failed_Scheduled_Action_Manager::log_action_scheduler_failure()](https://github.com/Automattic/woocommerce-subscriptions-core/blob/trunk/includes/class-wcs-failed-scheduled-action-manager.php#L77) should have special handling to not log/store failed trial end action scheduler errors that contain the message "not be executed as no callbacks are registered.".

##### Original description

A change to Action Scheduler now throws an error if a scheduled action has no callbacks. https://github.com/woocommerce/action-scheduler/pull/806
WooCommerce Subscriptions adds the action `woocommerce_scheduled_subscription_trial_end` which doesn't do anything by itself. It's there so other extensions can add something to happen before a trial ends. 

Since the Action Scheduler update to 3.5.0, we've seen sporadic reports of failed scheduled actions. The trial is ending, but it's throwing an error in Subscriptions. This causes the `html-failed-scheduled-action-notice.php` to display on admin pages and logs an error. 

`10-19-2022 @ 10:05:18 - scheduled action 55915 (subscription trial end) failed to finish processing due to the following exception: Scheduled action for woocommerce_scheduled_subscription_trial_end will not be executed as no callbacks are registered.
`

I'm not entirely certain if the action should be changed to prevent the error or if the failed scheduled action notice should omit these or have a different error message. But we're getting more tickets in Happiness about failed actions related to `woocommerce_scheduled_subscription_trial_end`, and this change to AS appears to be the root. 

## To Reproduce

1. Create a subscription with a free trial
1. Wait until the trial ends (or manually run the action for `woocommerce_scheduled_subscription_trial_end`)
1. See the error as a failed scheduled action

### Expected behavior
Since the trial ended successfully, I don't expect to see an error displayed on admin pages and in the error logs. 

### Actual behavior

An error displays that causes the merchant to believe the trial end didn't process correctly. 

## Product impact

- [X] Does this issue affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- [X] Does this issue affect WooCommerce Payments? yes/no/tbc, add issue ref

Confirmed that the action is in Subscriptions Core, so it will impact WooCommerce Subscriptions and WooCommerce Payments Subscriptions.

## Additional context

A few tickets: 
5680379-zen
5650349-zen
5672620-zen 
5692989-zen

**Comment by AashikP** [comment] 2022-11-08 02:28
Adding my findings as well in case someone else cannot replicate them:

[WooCommerce Subscriptions](https://woocommerce.com/products/woocommerce-subscriptions/?aff=10486&cid=1131038):

* I could only replicate this behavior on my local test site with Rank Math SEO plugin active
* I used Local by flywheel to test and changed the time on my iMac to trigger the scheduled actions. Not sure if that makes a difference

Note that even with the error message, the Subscription trial does end, and the payment for the Subscription will go through as long as they have a payment method saved for the Subscription.

**Comment by nicdwilson** [comment] 2022-11-08 20:33
5678860-zen

**Comment by darcie** [comment] 2022-11-08 20:39
> * I could only replicate this behavior on my local test site with Rank Math SEO plugin active

@AashikP I think this is due to an upgraded version of Action Scheduler included in Rank Math.

**Comment by nicdwilson** [comment] 2022-11-08 20:42
5691160-zen

**Comment by nicdwilson** [comment] 2022-11-08 20:42
Note that MailChimp and Sucuri plugins now also include the upgraded versions of Action Scheduler

**Comment by nicdwilson** [comment] 2022-11-08 21:31
5691504-zen

**Comment by paulostp** [comment] 2022-11-14 10:31
5708793-zen

**Comment by shevene** [comment] 2022-11-14 15:04
5710707-zen

**Comment by thisissandip** [comment] 2022-11-21 04:44
35601874-hc

**Comment by EjayhanFernandes** [comment] 2022-11-21 06:55
5727053-zen

**Comment by shevene** [comment] 2022-11-26 01:35
5742082-zen

**Comment by darcie** [comment] 2022-11-26 19:07
5735682-zen

**Comment by felipevelzani** [comment] 2022-11-28 18:44
5747934-zen

**Comment by shaunkuschel** [comment] 2022-12-02 01:41
5758905-zen

**Comment by solstudioim** [comment] 2022-12-02 07:26
Looks like in 5758905-zen, AS for WP Rocket is 3.5.2, so likely can be the cause.

**Comment by rossviviano** [comment] 2022-12-02 12:31
38424239-hc

**Comment by NathalyaVides** [comment] 2022-12-05 20:23
5748844-zen

**Comment by francoishvz** [comment] 2022-12-06 09:24
5766006-zen

**Comment by felipevelzani** [comment] 2022-12-07 15:34
38523620-hc

**Comment by darcie** [comment] 2022-12-07 18:41
5772085-zen

**Comment by csmcneill** [comment] 2022-12-07 19:13
@Automattic/helix Is this on y'all's radar?

cc @apenasjoao

**Comment by haszari** [comment] 2022-12-07 19:46
Would be good to see a screenshot of the error in admin to understand how impactful this is. @darcie can you add a screenshot of the error to the description (or any HE who lands on a ticket relating to this)?

It sounds like we should be able to fix this relatively easily, though I'm curious to better understand why the Action Scheduler behaviour changed; IMO it sounds harsh and surprising to throw an error.

I've added to our maintenance board, on the assumption we can make a small change to prevent these errors; no ETA for when we'd get to it.

**Comment by darcie** [comment] 2022-12-07 19:53
Yep! It generates the big subscription error on all admin pages: 

![jbzCVe.png](https://user-images.githubusercontent.com/318285/206281690-562bcf50-1968-4a6b-a450-5d971e48cd89.png)

It also generates errors in Scheduled Actions: 

![QxdPMw.png](https://user-images.githubusercontent.com/318285/206281777-3dcbfdce-2d2c-4091-b03f-d27caeb3b15a.png)

> IMO it sounds harsh and surprising to throw an error.

Agreed, I understand from reading the change what they were trying to fix, but a number of actions out there in various plugins are empty like this one.

**Comment by haszari** [comment] 2022-12-07 19:58
That was quick @darcie ! Don't like the look of that screenshot, hopefully we can tidy this up!!

**Comment by sukafia** [comment] 2022-12-13 09:02
5786064-zen

**Comment by rashedripon** [comment] 2022-12-13 14:14
5691160-zen

**Comment by csmcneill** [comment] 2022-12-14 21:51
17727480-hc

**Comment by raifd** [comment] 2022-12-29 08:01
5807847-zen

**Comment by jtobiesen** [comment] 2022-12-30 11:42
39178787-hc

**Comment by WillBrubaker** [comment] 2023-01-05 04:44
Got renewals not doing anything because of this in 5839084-zen 

![MleUVv.png](https://user-images.githubusercontent.com/2127470/210703356-84a1238d-ef46-4a02-88ac-5c310bf4a7b2.png)

> Scheduled action for woocommerce_scheduled_subscription_payment will not be executed as no callbacks are registered

FWIW, they've got mailpoet 4.3.1 which uses AS 3.5.2 currently

**Comment by joaodante** [comment] 2023-01-06 13:08
5843141-zen

**Comment by haszari** [comment] 2023-01-10 21:49
> Got renewals not doing anything because of this in 5839084-zen

@mattallan  (reviewer) can you take a quick look at this and confirm if there's any serious issue here we need to follow up? I'm not clear if this bug is e.g. potentially breaking renewals for regular WC Subscriptions users.

**Comment by mattallan** [comment] 2023-01-10 23:34
Hey all,

I've been able to confirm this issue after installing the Rank Math SEO plugin and then trying to run the `woocommerce_scheduled_subscription_trial_end` scheduled action.

![image](https://user-images.githubusercontent.com/2275145/211682998-15357e48-9d8b-4923-8adf-edefac8fc97b.png)

While there's no serious issue caused by this, I can understand the main concern here is store managers probably see this error notice and think something is broken.

What I think we'll need to do is update our [`WCS_Failed_Scheduled_Action_Manager::log_action_scheduler_failure()`](https://github.com/Automattic/woocommerce-subscriptions-core/blob/trunk/includes/class-wcs-failed-scheduled-action-manager.php#L77) function to have special handling to not log/store failed trial end action scheduler errors that contain the message "not be executed as no callbacks are registered.".

cc @haszari - a fix for this should be pretty small, however, there are no serious issues here apart from store managers seeing a big error notice on their admin pages whenever a subscription's trial end period is up 😕 This would be arguably annoying and if it's bringing in unnecessary support tickets we should probably look at fixing this soonish.

---

@WillBrubaker I can't reproduce the error in your screenshot with this happening to the subscriptions renewal hook:

> Scheduled action for woocommerce_scheduled_subscription_payment will not be executed as no callbacks are registered

The Subscriptions extension (both the main plugin and WC Pay Subscriptions) has callbacks attached to the `woocommerce_scheduled_subscription_payment` hook. The only way I can only reproduce this issue is if I have all versions of subscriptions completely disabled on my store (i.e. deactivate WC Subscriptions and WC Payments, then trigger the `woocommerce_scheduled_subscription_payment` hook)

In this case, this is intended behaviour.

**Comment by haszari** [comment] 2023-01-10 23:49
> a fix for this should be pretty small, however, there are no serious issues here apart from store managers seeing a big error notice on their admin pages whenever a subscription's trial end period is up 😕 This would be arguably annoying and if it's bringing in unnecessary support tickets we should probably look at fixing this soonish.

Thank you @mattallan ! I'll update the title / description to reflect next steps based on your investigation. Feel free to edit so it's clear.

I've relabelled as low priority, as trial periods are not universal, so this will not be impacting all merchants. 

I agree would be good to slot this into maintenance at some point, especially if we get more reports.

**Comment by WillBrubaker** [comment] 2023-01-12 03:30
FWIW the user in 5839084-zen got back to us. Their renewal ran fine after they downgraded mailpoet to an earlier version. I wonder if that's all just coincidental, though and perhaps WCS was briefly disabled which resulted in their problems.

**Comment by shevene** [comment] 2023-01-12 14:25
[5858328-zen](5858328-zd-woothemes)

**Comment by jacoswan** [comment] 2023-01-13 10:09
36725575-hc

**Comment by paulostp** [comment] 2023-01-15 10:25
5861646-zen

**Comment by kaushikasomaiya** [comment] 2023-01-16 09:26
5868953-zen

**Comment by AbhinavSakalle** [comment] 2023-01-17 08:23
39350427-hc

**Comment by igorhereira** [comment] 2023-01-17 14:56
5868951-zen

**Comment by kgeorgee** [comment] 2023-01-20 14:30
38092252-hc

**Comment by kgeorgee** [comment] 2023-01-26 13:46
36828262-hc

**Comment by ali911** [comment] 2023-01-26 14:12
I'm having the same issue and subscription payment is not charged after the next scheduled payment and the subscription goes on hold instead of renewal.

**Comment by gabriel-fuentes** [comment] 2023-01-30 18:39
35721663-hc

**Comment by Mxchael** [comment] 2023-02-01 01:45
5916331-zen

**Comment by WillBrubaker** [comment] 2023-02-02 00:41
5912810-zen

**Comment by csmcneill** [comment] 2023-02-06 03:54
> I'm having the same issue and subscription payment is not charged after the next scheduled payment and the subscription goes on hold instead of renewal.

@ali911 what you're experiencing isn't related to this issue. If you haven't already, please open a support request here: https://woocommerce.com/my-account/create-a-ticket/

Since GitHub is not a designated support channel, reaching out to us via the above link will allow us to better assist you :)

**Comment by lynnjat7** [comment] 2023-02-09 19:40
5944294-zen

**Comment by felipevelzani** [comment] 2023-02-22 13:11
40912417-hc

**Comment by madisoncmiller** [comment] 2023-02-22 16:36
37927818-hc

**Comment by zoupkat** [comment] 2023-03-02 20:06
Hi @mattallan & @haszari ! Is there perhaps an updated ETA on a fix after January 10? 
If not, would you say that a temporary workaround would be to just roll back a version if someone does not want to be dealing with the false errors anymore or you do not recommend that in this case?
Thanks!

**Comment by haszari** [comment] 2023-03-02 20:10
No ETA for fix though hopefully we can fix this in an upcoming release. 

> would you say that a temporary workaround would be to just roll back a version if someone does not want to be dealing with the false errors anymore or you do not recommend that in this case?

I would not recommend reverting/rolling back to avoid this message. The error message does no harm, so it's best just to ignore it.

**Comment by felipevelzani** [comment] 2023-03-03 07:32
Edited the description of this issue to update the steps to reproduce as Action Scheduler 3.5.x is now part of WooCommerce core.

Also, just sent a PR to hopefully close this issue. :)

**Comment by Brianmitchtay** [comment] 2023-03-03 19:10
6007433-zen

**Closed as completed** 2023-03-06 03:04 UTC
Labels: type: bug, good first issue, type: task, priority: low

**Comment by mattallan** [comment] 2023-03-06 03:12
Hey everyone 👋 We have just merged a fix for this issue which will go out in WC Subscriptions 5.0 (scheduled to release this week - internal post pdjTHR-2lo-p2).
Thanks for your patience on this one and thanks to @felipelousantos for getting up an initial PR
