### ISSUE TITLE
[HPOS] Unable to edit subscription in admin. JS not loaded.

### ISSUE THREAD

**Issue by brucealdridge** [Automattic/woocommerce-subscriptions-core#309] opened 2022-11-25 03:51 UTC
## Describe the bug

Unable to edit a subscription due to `woocommerce/assets/js/admin/meta-boxes-order.min.js` not being loaded,

Related to #297 

## To Reproduce

1. With HPOS on and enabled using PR #297 and https://github.com/woocommerce/woocommerce/pull/35658
2. Click on 'Subscriptions' in wp-admin
3. Click to view a subscription
4. Clicking the edit icons doesn't work

![image](https://user-images.githubusercontent.com/57298/203897632-d1aaec3a-5980-45c8-9f30-500c4900784b.png)

This is due to WC not enqueuing the relevant meta-box js
https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/admin/class-wc-admin-assets.php#L540-L543

Replacing with the following resolves the issue
```php
return in_array( str_replace( ['edit-', 'woocommerce_page_wc-orders--' ] , '', $screen_id ), wc_get_order_types( 'order-meta-boxes' ), true ) ||
	wc_get_page_screen_id( 'shop-order' ) === $screen_id;
```

**Comment by mattallan** [comment] 2022-12-23 02:44
I've tested this on the latest #297 changes and it looks like this has been fixed.

I think this commit fixed it: https://github.com/Automattic/woocommerce-subscriptions-core/commit/13e77a992bd104e3c1efa8c6a4d9faf6ee5f2c10

Since I can't reproduce it, I'm going to close this.

To test this I:
 1. Pulled latest `trunk` and enabled HPOS
 2. Purchased a subscription
 3. Visited the Edit Subscription admin page
 4. Modified the order items total
 5. Modified the billing schedule
 6. Pressed "Update" and confirmed the data was saved

**Closed as completed by mattallan** 2022-12-23 02:44 UTC
Labels: type: bug, compatibility: HPOS, Feature: Admin Screens
