### ISSUE TITLE
With COT enabled, multiple error logs after successfully paying for a failed renewal order

### ISSUE THREAD

**Issue by mattallan** [Automattic/woocommerce-subscriptions-core#198] opened 2022-08-11 06:55 UTC
## Describe the bug

While running through the "Renew a subscription which had an automatic renewal payment fail" test case on my COT enabled with syncing off store, I noticed these errors in the debug log.

```
[11-Aug-2022 06:15:30 UTC] PHP Notice:  Undefined offset: 469 in /srv/users/usereaea7e7b/apps/usereaea7e7b/public/wp-content/plugins/woocommerce-subscriptions-core/includes/class-wcs-cart-renewal.php on line 433
[11-Aug-2022 06:15:30 UTC] PHP Notice:  Trying to access array offset on value of type null in /srv/users/usereaea7e7b/apps/usereaea7e7b/public/wp-content/plugins/woocommerce-subscriptions-core/includes/class-wcs-cart-renewal.php on line 435
[11-Aug-2022 06:15:30 UTC] PHP Notice:  Trying to access array offset on value of type null in /srv/users/usereaea7e7b/apps/usereaea7e7b/public/wp-content/plugins/woocommerce-subscriptions-core/includes/class-wcs-cart-renewal.php on line 455
[11-Aug-2022 06:15:30 UTC] PHP Notice:  Trying to access array offset on value of type null in /srv/users/usereaea7e7b/apps/usereaea7e7b/public/wp-content/plugins/woocommerce-subscriptions-core/includes/class-wcs-cart-renewal.php on line 456
[11-Aug-2022 06:15:30 UTC] PHP Warning:  Division by zero in /srv/users/usereaea7e7b/apps/usereaea7e7b/public/wp-content/plugins/woocommerce-subscriptions-core/includes/class-wcs-cart-renewal.php on line 456
[11-Aug-2022 06:15:30 UTC] PHP Notice:  Trying to access array offset on value of type null in /srv/users/usereaea7e7b/apps/usereaea7e7b/public/wp-content/plugins/woocommerce-subscriptions-core/includes/class-wcs-cart-renewal.php on line 463
[11-Aug-2022 06:15:30 UTC] PHP Notice:  Trying to access array offset on value of type null in /srv/users/usereaea7e7b/apps/usereaea7e7b/public/wp-content/plugins/woocommerce-subscriptions-core/includes/class-wcs-cart-renewal.php on line 467
[11-Aug-2022 06:15:31 UTC] PHP Notice:  Undefined offset: 469 in /srv/users/usereaea7e7b/apps/usereaea7e7b/public/wp-content/plugins/woocommerce-subscriptions-core/includes/class-wcs-cart-renewal.php on line 433
[11-Aug-2022 06:15:31 UTC] PHP Notice:  Trying to access array offset on value of type null in /srv/users/usereaea7e7b/apps/usereaea7e7b/public/wp-content/plugins/woocommerce-subscriptions-core/includes/class-wcs-cart-renewal.php on line 435
[11-Aug-2022 06:15:31 UTC] PHP Notice:  Trying to access array offset on value of type null in /srv/users/usereaea7e7b/apps/usereaea7e7b/public/wp-content/plugins/woocommerce-subscriptions-core/includes/class-wcs-cart-renewal.php on line 455
[11-Aug-2022 06:15:31 UTC] PHP Notice:  Trying to access array offset on value of type null in /srv/users/usereaea7e7b/apps/usereaea7e7b/public/wp-content/plugins/woocommerce-subscriptions-core/includes/class-wcs-cart-renewal.php on line 456
[11-Aug-2022 06:15:31 UTC] PHP Warning:  Division by zero in /srv/users/usereaea7e7b/apps/usereaea7e7b/public/wp-content/plugins/woocommerce-subscriptions-core/includes/class-wcs-cart-renewal.php on line 456
[11-Aug-2022 06:15:31 UTC] PHP Notice:  Trying to access array offset on value of type null in /srv/users/usereaea7e7b/apps/usereaea7e7b/public/wp-content/plugins/woocommerce-subscriptions-core/includes/class-wcs-cart-renewal.php on line 463
[11-Aug-2022 06:15:31 UTC] PHP Notice:  Trying to access array offset on value of type null in /srv/users/usereaea7e7b/apps/usereaea7e7b/public/wp-content/plugins/woocommerce-subscriptions-core/includes/class-wcs-cart-renewal.php on line 467
```

From what I could tell everything worked as expected, the subscription was active and the failed order was set to processing.
No matter what I tried, I also **couldn't reproduce** this a second time using the same or similar steps, so I'm reluctant to open an issue for this.

I haven't looked at the lines of code throwing the errors yet so before digging into this issue, we should confirm the bug can be reproduced. I'm also not even sure it's related to COT but I'll label it as high priority for us to investigate further. 

## To Reproduce

1. Enable COT on your store and turn off order data syncing
2. Purchase a subscription
3. Go into My Account > Subscriptions > View the recent Subscription > change payment method
4. Change the payment method to a declining card i.e `4000000000000341`
5. Process a renewal order for the subscription
6. Make sure the payment fails and the subscription is on-hold
7. Go into My Account > Subscriptions > View the on-hold Subscription
8. Scroll down to the related orders and pay for the failed order using a successful card
9. Check logs for the above error

Like I said above, after seeing this error once I couldn't reproduce it so it's possible this issue could be closed off if it can't be reproduced.

I was thinking maybe the WC cart session was storing incorrect data (i.e. cart data from one of the other multisite test stores) and tried to build the cart with this data but I'm just spit-balling.

### Expected behavior

No error logs/PHP notices when paying for a failed renewal order

**Comment by shendy-a8c** [comment] 2022-11-21 05:16
Step to reproduce number 6, `Make sure the payment fails and the subscription is on-hold`, does not happen because of the notices as reported in [With COT enabled, multiple PHP notices are displayed when updating/saving an order linked to a subscription](https://github.com/Automattic/woocommerce-subscriptions-core/issues/196).

**Comment by shendy-a8c** [comment] 2022-11-23 08:36
Since subscription admin page is still broken, I executed this code in [WP Console](https://wordpress.org/plugins/wp-console/):

```
$subscription = wcs_get_subscription( 1 );
$subscription->update_status( 'active' );
do_action( 'woocommerce_scheduled_subscription_payment', $subscription->get_id() );
```

where `1` is the subcription id for step 5 `Process a renewal order for the subscription` and I could get the notices in the debug log:

```
[23-Nov-2022 06:45:00 UTC] PHP Notice:  Undefined offset: 23 in {path}/woocommerce-subscriptions-core/includes/class-wcs-cart-renewal.php on line 435
[23-Nov-2022 06:45:00 UTC] PHP Notice:  Trying to access array offset on value of type null in {path}/woocommerce-subscriptions-core/includes/class-wcs-cart-renewal.php on line 437
[23-Nov-2022 06:45:00 UTC] PHP Notice:  Trying to access array offset on value of type null in {path}/woocommerce-subscriptions-core/includes/class-wcs-cart-renewal.php on line 457
[23-Nov-2022 06:45:00 UTC] PHP Notice:  Trying to access array offset on value of type null in {path}/woocommerce-subscriptions-core/includes/class-wcs-cart-renewal.php on line 465
[23-Nov-2022 06:45:00 UTC] PHP Notice:  Trying to access array offset on value of type null in {path}/woocommerce-subscriptions-core/includes/class-wcs-cart-renewal.php on line 469
[23-Nov-2022 06:45:01 UTC] PHP Notice:  Undefined offset: 23 in {path}/woocommerce-subscriptions-core/includes/class-wcs-cart-renewal.php on line 435
[23-Nov-2022 06:45:01 UTC] PHP Notice:  Trying to access array offset on value of type null in {path}/woocommerce-subscriptions-core/includes/class-wcs-cart-renewal.php on line 437
[23-Nov-2022 06:45:01 UTC] PHP Notice:  Trying to access array offset on value of type null in {path}/woocommerce-subscriptions-core/includes/class-wcs-cart-renewal.php on line 457
[23-Nov-2022 06:45:01 UTC] PHP Notice:  Trying to access array offset on value of type null in {path}/woocommerce-subscriptions-core/includes/class-wcs-cart-renewal.php on line 465
[23-Nov-2022 06:45:01 UTC] PHP Notice:  Trying to access array offset on value of type null in {path}/woocommerce-subscriptions-core/includes/class-wcs-cart-renewal.php on line 469
[23-Nov-2022 06:49:21 UTC] wcs_renewal_order_meta_query is deprecated since version subscriptions-core 2.5.0! Use wc_subscriptions_renewal_order_data instead.
```

However, I could only reproduce that *once* and never get it again. Very weird. I don't know what I did differently to get that notice. I tested on a clean JN site as well and don't see those notices, so closing for now as it's not reproducible with current `trunk`.

**Closed as completed by shendy-a8c** 2022-11-23 08:36 UTC
Labels: type: bug, priority: high, compatibility: HPOS
