### ISSUE TITLE
Subscription List Table does not sort properly with HPOS

### ISSUE THREAD

**Issue by jb510** [Automattic/woocommerce-subscriptions-core#471] opened 2023-07-14 18:07 UTC
## Describe the bug
Sorting subscriptions by clicking on their column headings does not work correctly. Sometimes it has no effect (starting date) sometimes one gets a random order (next payment date).  This is with HPOS enabled, haven't tested recently without but assumed it used to work.

## To Reproduce
Enable HPOS
Go to the active subscriptions list page /?page=wc-orders--shop_subscription&status=wc-active
Sort by "next payment date" notice in the screenshot "in 2 days" shows up in first and fourth position, with "in 6 days" and "July 26th" in between the two.

Click on the "Start Date" heading, and nothing at all seems to happen. It does not sort, nor does it reverse/descending sort after repeated clicks.

### Expected behavior
Clicking on column headers should sort correctly when HPOS is enabled.

### Actual behavior
Clicking on column headers is either doing nothing, sorting on the wrong column, or sorting completely incorrectly.

## Product impact
Impossible to clearly see which subscriptions need attention.

- [yes] Does this issue affect WooCommerce Subscriptions?

![CleanShot 2023-07-14 at 10 57 33@2x](https://github.com/Automattic/woocommerce-subscriptions-core/assets/801241/e0d3850c-f140-4950-b292-74abee5502ad)

**Comment by kaushikasomaiya** [comment] 2023-11-29 11:11
7368486-zen

**Comment by kaushikasomaiya** [comment] 2023-11-29 11:12
@james-allan @mattallan Just surfacing this for attention.

**Comment by james-allan** [comment] 2023-11-30 08:58
Thanks for the ping @kaushikasomaiya. 

This may require some changes to WooCommerce core. I've taken a look at how we can order the list table results however it's rather restrictive. 

The WC core function, `OrdersTableQuery::process_orderby()`, has no entry points where Woo Subscriptions can tell WooCommerce how we want to order the list of results by a custom meta key. @mattallan mentioned that this may have been raised with the core team already but couldn't recall if this is the exact same issue. We'll double check and look into whether this is something that they are already aware of.

**Comment by james-allan** [comment] 2023-12-04 00:02
>  @mattallan mentioned that this may have been raised with the core team already but couldn't recall if this is the exact same issue. We'll double check and look into whether this is something that they are already aware of.

For internal use here's the thread where we discussed in p1672967764366439-slack-C9QDV4TL4. Nothing of noteworthy for public folks, just the report. 

WC added support for it here: https://github.com/woocommerce/woocommerce/pull/36403 so we'll need to look into those changes and see if we can integrate with them. 

Just noting that this issue is a duplicate of #200.

**Closed as completed** 2024-01-11 04:49 UTC
Labels: type: bug
