### ISSUE TITLE
PHP fatal error when $checkout_fields['shipping'] is null

### ISSUE THREAD

**Issue by slapic** [Automattic/woocommerce-subscriptions-core#176] opened 2022-05-27 03:52 UTC
## Describe the bug
In the file
woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/includes/class-wcs-cart-renewal.php, line 487 you merge $checkout_fields['billing'] and $checkout_fields['shipping'] as arrays. However, if one of these is null (mostly the shipping in a digital store), it triggers a PHP fatal error. The code should check if these are both arrays.

## To Reproduce

$checkout_fields['shipping'] = null;
Try to renew or manually pay for an on-hold subscription on the frontend.

### Expected behavior

Don't try to merge $checkout_fields['shipping'] if it's null.

### Actual behavior

If $checkout_fields['shipping'] is null, there'll be a PHP fatal error in woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/includes/class-wcs-cart-renewal.php:487

## Product impact

- [ yes] Does this issue affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- [ tbc] Does this issue affect WooCommerce Payments? yes/no/tbc, add issue ref

## Additional context

5239857-zd-woothemes

**Comment by haszari** [comment] 2023-01-12 22:19
@mattallan  (current reviewer) – Can you test to confirm this? I'm thinking something like:

- Set up digital subscription product (no shipping).
- Purchase, subscribe.
- Put subscription on hold.
- Renew or manual payment to resume.
- 🔴 Fatal error?

(Or @slapic please comment with reproduce steps on a basic site with WC core and either WC Subscriptions or WCPay.)

If it's possible to trigger a fatal in regular use we should prioritise fixing this.

**Comment by haszari** [comment] 2023-01-25 01:42
Looks like this fell off the radar. @james-allan can you reproduce this to confirm?

**Comment by james-allan** [comment] 2023-01-25 05:22
I haven't been able to reproduce this. 

We only support back to WC 6.0 but on all versions since WC 3.0 we call `WC()->checkout()->get_checkout_fields( 'shipping' )` which will always return a set of shipping fields irrespective of the environment (shipping enabled vs disabled) and the cart contents (virtual vs physical products).

If this is causing the error as described then I suspect the author is using an old version of WC or the condition `is_callable( array( WC()->checkout(), 'get_checkout_fields' ) )` is failing and this is falling through to an old (pre WC 3.0) way of getting these fields.

@slapic can you confirm which version of WC you were using to get this error? 

In the meantime I'm going to close this as I cannot replicate it and after investigation cannot understand how this would occur unless an unsupported version of WC was being used.

**Closed as completed by james-allan** 2023-01-25 05:22 UTC
Labels: type: bug, needs feedback
